from typing import TypedDict, List


class ResearchState(TypedDict):
    topic: str                  # input of a user
    steps: List[str]            # step generated by planner
    results: List[str]          # content fetched/generated by LLM
    output: str                 # outputs / and final o/p
    quality_score: float        # checking the quality of o/p if it passes the check or not
    iteration_count: int        # for looping or to stop loop
