from typing import TypedDict, List, Annotated
import operator


class ResearchState(TypedDict):

    # input of a user
    topic: str
    # step generated by planner
    steps: List[str]
    # content fetched/generated by LLM
    results: Annotated[List[str], operator.add]
    # outputs / and final o/p
    output: str
    # checking the quality of o/p if it passes the check or not
    quality_score: float
    # for looping or to stop loop
    iteration_count: int
